server.port=${PORT:8080}
server.address=0.0.0.0

spring.datasource.url=jdbc:postgresql://dpg-d7d7sl3eo5us73fjpe1g-a/alumni_db_9kty
spring.datasource.username=alumni_db_9kty_user
spring.datasource.password=4GbUJq4nTWHHcA2LWYTea92htOk75H6K
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

app.jwt.secret=campusconnectsecretkey12345678901234567890123456789012
app.jwt.expiration-ms=86400000