

spring.datasource.url=jdbc:mysql://junction.proxy.rlwy.net:26263/railway
spring.datasource.username=root
spring.datasource.password=qntWcoEcWHDujhNIbMzvJBreegktjKet

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
app.jwt.secret=campusconnectsecretkey12345678901234567890123456789012
app.jwt.expiration-ms=86400000

# Optional (safe)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect